version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TEST_REDIS_URL: redis://redis:6379
    command: npm run test:ci
    depends_on:  
      - redisq
  redis:
    image: "redis:alpine"