name: deploy

on:
    push:
        branches:
            - main
        

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
            - name: Checkout reposiroty
              uses: actions/checkout@v3
            - name: Build and test with Docker Compose
              run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository # repostiry를 열어야 거기에서의 파일을 사용할 수있다 , 나는 쉘 스크립트를 쓸 거기 때문에 , checkout으로 열어야한다 
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::306593213077:role/no_branch_OIDC
          role-session-name: smapleSessionName
          aws-region: ap-northeast-2

      - name: Grant execute permission for git_api_status.sh #내 local에서의 권한과 상관없이 , runs-on ubuntu 이기 때문에 , 권한 x 추가해야 
        run: chmod +x ./git_api_status.sh

      - name: Delay execution for 30 seconds
        run: sleep 60s
      

      - name: Run custom script
        run: ./git_api_status.sh
        env:
          TOKEN: ${{ secrets.BASH_SHELL_TOKEN }}

  
               

